# .yarnrc

nodeLinker: node-modules

npmScopes:
  solitics:
    npmRegistryServer: "https://soliticsmobilesdk.jfrog.io/artifactory/api/npm/react.native.solitics.mobile.releases/"
    npmAuthToken: "token"
    npmAlwaysAuth: true
