# .yarnrc

nodeLinker: node-modules

npmScopes:
  solitics:
    npmAlwaysAuth: false
    npmRegistryServer: "https://soliticsmobilesdk.jfrog.io/artifactory/api/npm/react.native.solitics.mobile.releases-local/"
